all: compile link

compile:
	g++ -I"D:\SFML-3.0.2-windows-gcc-14.2.0-mingw-32-bit\SFML-3.0.2\src\include" -c Programs/*.cpp

link:
	g++ *.o -o main -Lsrc/lib -lsfml-graphics -lsfml-window -lsfml-system -lopengl32 -lsfml-audio